apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: jsapi
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: kind/healthcheck:30ce3c10482acd680291767beb06d2f46f8edd11e7653735ba8cefe31a219690
  # You can allow the bot to connect to other challenges internally.
  # This can be useful during testing so that you don't have to make your
  # challenge public.
  # The challenge will be reachable at $name.default.svc.cluster.local or
  # simply at $name with the default k8s search list.
  #allowConnectTo:
  #  - otherchallenge

  image: kind/challenge:973121b3618bba2e99b3738fec43ddd01b14e10e5ac90767bd15bf9b0ca5361c
